---
kind: pipeline
type: docker
name: default

platform:
  arch: arm64

steps:
  - name: docker build
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      - DOCKER_BUILDKIT=1 docker build -t rossmaclean/mail-client:drone-test .

volumes:
  - name: dockersock
    host:
      path: /var/run/