---
kind: pipeline
type: docker
name: default

steps:
  - name: docker build
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      - docker buildx -t rossmaclean/mail-client:drone-test .

volumes:
  - name: dockersock
    host:
      path: /var/run/