name: Master CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  APP: mail-client

jobs:
  build_push_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: "echo Version: ${GITHUB_SHA::7}"
      - run: docker login --username rossmaclean --password ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker build -t rossmaclean/$APP:${GITHUB_SHA::7} .
      - run: docker push rossmaclean/$APP:${GITHUB_SHA::7}

  deploy_staging:
    needs: build_push_image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - run: npm i -g cloudron
      - run: cloudron update --server my.rossmac.co.uk --token ${{ secrets.CLOUDRON_TOKEN }} --app $APP.staging.rossmac.co.uk --image rossmaclean/$APP:${GITHUB_SHA::7}
