name: Master CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build_push_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: "echo Version: ${GITHUB_SHA::7}"
      - run: docker login --username rossmaclean --password ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker build -t rossmaclean/mail-client:${GITHUB_SHA::7} .
      - run: docker push rossmaclean/mail-client:${GITHUB_SHA::7}
