name: Master CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  VERSION: '${GITHUB_SHA::7}'
  APP: mail-client

jobs:
  build_push_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: "echo Version: $VERSION"
      - run: docker login --username rossmaclean --password ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker build -t rossmaclean/$APP:$VERSION .
      - run: docker push rossmaclean/$APP:$VERSION

  deploy_prod:
    needs: build_push_image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - run: npm i -g cloudron
      - run: cloudron update --server my.rossmac.co.uk --token ${{ secrets.CLOUDRON_TOKEN }} --app $APP.rossmac.co.uk --image rossmaclean/$APP:$VERSION
